language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install pytest pytest-cov codecov pycodestyle
install:
  - pip install -e .
script:
  - pycodestyle
  - pytest -vvv --cov=dictmatching
after_success:
  - codecov
