language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
before_install:
  - pip install pytest pytest-cov codecov pep8
install:
  - pip install -e .
script:
  - pep8
  - pytest -vvv --cov=dictmatching
after_success:
  - codecov
